name: API Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test code
        uses: actions/checkout@v3

      - name: Start API container
        run: docker run -d -p 8000:8000 --name fastapi-test-api gurki1632/dummy-api:latest

      - name: Wait for API to be ready
        run: sleep 60

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Maven tests
        run: mvn test

      - name: Cleanup
        run: |
          docker stop fastapi-test-api
          docker rm fastapi-test-api
